name: Update stats cards

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Generate stats card
        uses: jstrimpel/github-stats-transparent@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          user: PrathushPillai
          output: profile/stats.svg

      - name: Generate top-langs card
        uses: jstrimpel/github-stats-transparent@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          user: PrathushPillai
          card: top-langs
          output: profile/top-langs.svg

      - name: Commit cards
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@users.noreply.github.com"
          git add profile/*.svg
          git commit -m "Update stats cards" || exit 0
          git push
